### ISSUE TITLE
TFS / TFVC / Azure extension broken

### ISSUE THREAD

**Issue by kieferrm** [microsoft/azure-repos-vscode#477]
Moved from https://github.com/Microsoft/vscode/issues/68015 originally posed by @onelifenyc.

- VSCode Version: 1.31.0
- OS Version: windows 10 pro 

Steps to Reproduce:

1. Launch project (folder)
2. TFS connection does not work
3. Try to authenticate - dies silently after correct password is entered 

In reality on startup of vscode Log(Window) shows the following:

```
[2019-02-06 17:43:35.450] [renderer1] [error] Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
	at TfvcSCMProvider.onDidModelChange (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\tfvcscmprovider.js:128:44)
	at e.fire (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at Model.<anonymous> (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:188:31)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:8:58)
```

Does this issue occur when all extensions are disabled?: N/A

----

Extra details:
I did put back 1.30.0. The Azure Repos (the extension in question) needed to authenticate again but it did so successfully.

However, I did see the same error in my original post in the Log(Window):

```
[2019-02-06 17:54:09.856] [renderer1] [error] Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
	at TfvcSCMProvider.onDidModelChange (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\tfvcscmprovider.js:128:44)
	at e.fire (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:238)
	at Model.<anonymous> (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:188:31)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:8:58)
	at <anonymous>
```

**Comment by mczachurski** [comment]
In my company whole team have this error after upgrade VS Code to 1.31.0. It makes work very difficult.

**Comment by lorond** [comment]
Looks like initial error is
```
Error: Failed Request: Unauthorized(401) - http://host/tfs/collection/_apis/tfvc/branches
	at processResponse (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\node_modules\vso-node-api\RestClient.js:59:18)
	at C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\node_modules\vso-node-api\RestClient.js:147:13
	at handleResult (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\node_modules\vso-node-api\HttpClient.js:157:17)
	at IncomingMessage.<anonymous> (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\node_modules\vso-node-api\HttpClient.js:168:17)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```
Thrown here: https://github.com/Microsoft/azure-repos-vscode/blob/04e9e85a5673f507a96e81d41aba7aec1e682b11/src/extensionmanager.ts#L297
